#!/usr/bin/env bash
set -euo pipefail

##############################################################################
##  SignalDeck Landing Page — Nginx Bootstrap
##
##  Usage:
##    sudo bash install.sh <domain> [cert-path] [key-path]
##
##  Example:
##    sudo bash install.sh example.com
##    sudo bash install.sh example.com /etc/ssl/cloudflare/origin.pem /etc/ssl/cloudflare/origin.key
##
##  This script prepares the server only:
##    - creates the static site directory
##    - installs the Nginx vhost
##    - points Nginx at /var/www/cypress-dashboard-site/public
##
##  Upload the built ./public output separately from your local machine.
##
##  SSL uses a Cloudflare Origin Certificate. Before running this script:
##    1. Generate an Origin Certificate in Cloudflare Dashboard
##       → SSL/TLS → Origin Server → Create Certificate
##    2. Save the certificate to:   /etc/ssl/cloudflare/origin.pem
##    3. Save the private key to:   /etc/ssl/cloudflare/origin.key
##    4. Set Cloudflare SSL mode to "Full (strict)"
##############################################################################

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}✓${NC}  $*"; }
info() { echo -e "  ${CYAN}→${NC}  $*"; }
die()  { echo -e "  ${RED}✗${NC}  $*" >&2; exit 1; }

if [[ $# -lt 1 ]]; then
    die "Usage: sudo bash install.sh <domain> [cert-path] [key-path]"
fi

DOMAIN="${1}"
DEFAULT_SSL_CERT="/etc/ssl/cloudflare/origin.pem"
DEFAULT_SSL_KEY="/etc/ssl/cloudflare/origin.key"
SSL_CERT="${2:-$DEFAULT_SSL_CERT}"
SSL_KEY="${3:-$DEFAULT_SSL_KEY}"

APP_USER="www-cypress-site"
APP_DIR="/var/www/cypress-dashboard-site"
PUBLIC_DIR="${APP_DIR}/public"
NGINX_AVAILABLE="/etc/nginx/sites-available/cypress-dashboard-site"
NGINX_ENABLED="/etc/nginx/sites-enabled/cypress-dashboard-site"

if [[ $EUID -ne 0 ]]; then
    die "This script must be run as root (use sudo)"
fi

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   SignalDeck Site — Bootstrap                        ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
info "Domain    : ${DOMAIN}"
info "Directory : ${PUBLIC_DIR}"
info "User      : ${APP_USER}"
info "SSL cert  : ${SSL_CERT}"
info "SSL key   : ${SSL_KEY}"
echo ""

info "Checking dependencies..."
for cmd in nginx openssl rsync; do
    if ! command -v "$cmd" &>/dev/null; then
        die "'$cmd' is not installed. Please install it and re-run."
    fi
    ok "$cmd found ($(${cmd} --version 2>&1 | head -1))"
done

info "Checking Cloudflare Origin Certificate..."
if [[ ! -f "$SSL_CERT" ]]; then
    die "Certificate not found at: ${SSL_CERT}"
fi

if [[ ! -f "$SSL_KEY" ]]; then
    die "Private key not found at: ${SSL_KEY}"
fi

chmod 600 "$SSL_KEY"

info "Validating certificate and private key..."
if ! openssl x509 -in "$SSL_CERT" -noout >/dev/null 2>&1; then
    die "The certificate file is not a valid PEM X.509 certificate: ${SSL_CERT}"
fi

if ! openssl pkey -in "$SSL_KEY" -noout >/dev/null 2>&1; then
    die "The private key file is not a valid PEM private key: ${SSL_KEY}"
fi

if ! diff \
    <(openssl x509 -in "$SSL_CERT" -pubkey -noout 2>/dev/null) \
    <(openssl pkey -in "$SSL_KEY" -pubout 2>/dev/null) \
    >/dev/null; then
    die "The SSL certificate and private key do not match."
fi

ok "Certificate: ${SSL_CERT}"
ok "Private key: ${SSL_KEY}"
ok "Certificate and private key match"

info "Creating system user '${APP_USER}'..."
if id "$APP_USER" &>/dev/null; then
    ok "User '${APP_USER}' already exists"
else
    useradd \
        --system \
        --no-create-home \
        --shell /usr/sbin/nologin \
        --comment "SignalDeck Static Site" \
        "$APP_USER"
    ok "User '${APP_USER}' created"
fi

usermod -aG "$APP_USER" www-data 2>/dev/null || true

info "Setting up static site directory..."
mkdir -p "$PUBLIC_DIR"
chown -R "${APP_USER}:www-data" "$APP_DIR"
find "$APP_DIR" -type d -exec chmod 750 {} \;
find "$APP_DIR" -type f -exec chmod 640 {} \; 2>/dev/null || true
ok "Directories ready"

info "Writing Nginx configuration..."

cat > "$NGINX_AVAILABLE" <<NGINX
##
## Generated by install.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
## Domain:   ${DOMAIN}
## SSL:      Cloudflare Origin Certificate
##

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    root  ${PUBLIC_DIR};
    index index.html;

    access_log /var/log/nginx/cypress-site.access.log;
    error_log  /var/log/nginx/cypress-site.error.log warn;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location ~* \.(css|js|woff|woff2|ttf|eot)\$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp)\$ {
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
    }

    add_header X-Frame-Options        "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy        "strict-origin-when-cross-origin" always;

    gzip on;
    gzip_vary on;
    gzip_types text/plain text/css application/javascript image/svg+xml;
    gzip_min_length 1024;
}
NGINX

ok "Nginx config written to ${NGINX_AVAILABLE}"

ln -sf "$NGINX_AVAILABLE" "$NGINX_ENABLED"
ok "Site enabled"

info "Testing Nginx configuration..."
if nginx -t 2>&1; then
    ok "Nginx config valid"
else
    die "Nginx config test failed — check the output above"
fi

info "Reloading Nginx..."
systemctl reload nginx
ok "Nginx reloaded"

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   Bootstrap complete!                                ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${GREEN}→${NC}  https://${DOMAIN}"
echo ""
echo -e "  Next step from your local machine:"
echo -e "    npm run build"
echo -e "    rsync -av --delete ./public/ user@server:${PUBLIC_DIR}/"
echo ""
echo -e "  Reminder: Cloudflare SSL/TLS mode must be set to ${CYAN}Full (strict)${NC}"
echo ""
